set tabstop=4
let mapleader = ","
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
filetype indent on
set number
set relativenumber

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Move between buffers
nnoremap <silent> <C-x> :bnext<CR>
nnoremap <silent> <C-z> :bprev<CR>

" Better tab switching
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Copy the whole file
nnoremap <C-c> :%y+<CR>

" Quick save & exit
nmap <leader>w :w!<CR>
nmap <leader>q :q<CR>

" Template for Competitive Programming
autocmd BufNewFile *.cpp 0r ~/.vim/templates/tmp.cpp

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'preservim/nerdtree'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'vimwiki/vimwiki'
call plug#end()

" Colors
set termguicolors
set bg=dark
colorscheme gruvbox
