set tabstop=4
let mapleader = ","
set softtabstop=4
set shiftwidth=4
set foldmethod=indent
set foldlevel=99
set expandtab
set smartindent
filetype indent on
set number
set relativenumber
syntax on

nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Move between buffers
nnoremap <silent> <C-x> :bnext<CR>
nnoremap <silent> <C-z> :bprev<CR>

" Better tab switching
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Copy the whole file
nnoremap <C-c> :%y+<CR>

" Quick save & exit
nmap <leader>w :w!<CR>
nmap <leader>q :q<CR>

" Template for Competitive Programming
autocmd BufNewFile *.cpp 0r ~/.vim/templates/tmp.cpp

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'dense-analysis/ale'
Plug 'altercation/vim-colors-solarized'
Plug 'Valloric/YouCompleteMe'
call plug#end()

" Toggle between dark and light mode
call togglebg#map("<F5>")

" Colors
set background=dark

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48:2;%lu;%lu;%lum"

" vim-airline settings
let g:airline_solarized_bg='dark'
let g:airline_theme='angr'
